version: '3'

services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - default

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - default

  config-server:
    image: indiagator/configserver:16aug1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8071/actuator/health" ]
      interval: 10s
      timeout: 12s
      retries: 3
    networks:
      - default
      - proxy

  eureka-server:
    image: indiagator/eurekaserver:16aug1prod
    ports:
      - target: 8070
      - published: 8070
      - mode: host
    depends_on:
      - config-server
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8070/actuator/health" ]
      interval: 10s
      timeout: 12s
      retries: 3
    networks:
      - default
      - proxy

  analytics-service:
    image: indiagator/analyticservice:18aug1prod
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8099/actuator/health" ]
      interval: 10s
      timeout: 12s
      retries: 3

    depends_on:
      - config-server
      - eureka-server
      - kafka
    networks:
      - default

  auth-service:
    image: indiagator/authservice:17aug1prod
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8095/actuator/health" ]
      interval: 10s
      timeout: 12s
      retries: 3

    depends_on:
      - config-server
      - eureka-server
      - kafka
    networks:
      - default


  gateway-server:
    image: indiagator/gatewayserver:17aug1prod
    ports:
      - target: 8072
      - published: 8072
      - mode: host
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8072/actuator/health" ]
      interval: 10s
      timeout: 12s
      retries: 3
    depends_on:
      - config-server
      - eureka-server
    networks:
      - default
      - proxy


  zipkin-server:
    image: 'openzipkin/zipkin'
    ports:
      - '9411:9411'
    networks:
      - default

networks:
  default:
    external: false
  proxy:
    external: true




