

services:

  config-server:
    image: indiagator/configserver:16aug1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8071/actuator/health" ]
      interval: 10s
      timeout: 12s
      retries: 3
      start_period: 3s

  eureka-server:
    image: indiagator/eurekaserver:16aug1prod
    ports:
      - "8070:8070"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8070/actuator/health" ]
      interval: 10s
      timeout: 12s
      retries: 3
      start_period: 4s
    depends_on:
      config-server:
        condition: service_healthy

  gateway-server:
    image: indiagator/gatewayserver:17aug1prod
    ports:
      - "8072:8072"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8072/actuator/health" ]
      interval: 10s
      timeout: 12s
      retries: 3
      start_period: 4s
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  auth-service:
    image: indiagator/authservice:17aug1prod
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8070/actuator/health" ]
      interval: 10s
      timeout: 12s
      retries: 3
      start_period: 4s
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      gateway-server:
        condition: service_started

  seller-service:
    image: indiagator/sellerservice:16aug1prod
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8092/actuator/health" ]
      interval: 10s
      timeout: 12s
      retries: 3
      start_period: 4s
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      gateway-server:
        condition: service_started

  buyer-service:
    image: indiagator/buyerservice:17aug1prod
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8093/actuator/health" ]
      interval: 10s
      timeout: 12s
      retries: 3
      start_period: 4s
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      gateway-server:
        condition: service_started

  offer-service:
    image: indiagator/offerservice:17aug1prod
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8091/actuator/health" ]
      interval: 10s
      timeout: 12s
      retries: 3
      start_period: 4s
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      gateway-server:
        condition: service_started

  order-service:
    image: indiagator/orderservice:17aug1prod
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8096/actuator/health" ]
      interval: 10s
      timeout: 12s
      retries: 3
      start_period: 4s
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      gateway-server:
        condition: service_started

  payment-service:
    image: indiagator/paymentservice:17aug1prod
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8097/actuator/health" ]
      interval: 10s
      timeout: 12s
      retries: 3
      start_period: 4s
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      gateway-server:
        condition: service_started

  logistic-service:
    image: indiagator/logisticservice:17aug1prod
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8094/actuator/health" ]
      interval: 10s
      timeout: 12s
      retries: 3
      start_period: 4s
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      gateway-server:
        condition: service_started





