
services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  redis:
    image: redis:latest
    ports:
      - '6380:6379'
    volumes:
      - redis-data:/data

  config-server:
    build: . # image: indiagator/configserver:sep23dev1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8071/actuator/health" ]
      interval: 10s
      timeout: 12s
      retries: 3
      start_period: 10s
    networks:
      default:
        aliases:
          - "config-server"
    volumes:
      - logs:/var/log/

  eureka-server:
    image: indiagator/eurekaserver:16aug1prod 
    ports:
      - "8070:8070"
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8070/actuator/health" ]
      interval: 10s
      timeout: 12s
      retries: 3
      start_period: 10s
    networks:
      default:
        aliases:
          - "eureka-server"

  auth-service-cache:
    image: indiagator/authservicecache:sep23prod3
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8881/actuator/health" ]
      interval: 10s
      timeout: 12s
      retries: 3
      start_period: 10s
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      kafka:
        condition: service_started

  auth-service:
    image: indiagator/authservice:sep23prod3
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8086/actuator/health" ]
      interval: 10s
      timeout: 12s
      retries: 3
      start_period: 10s
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      kafka:
        condition: service_started
    volumes:
      - logs:/var/log

  gateway-server:
    image: indiagator/gatewayserver:swarm1
    ports:
      - "8072:8072"
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8072/actuator/health" ]
      interval: 10s
      timeout: 12s
      retries: 3
      start_period: 10s
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy

  zipkin-server:
    image: 'openzipkin/zipkin'
    ports:
      - '9411:9411'



volumes:
  redis-data: #docker will decide the path on the HD because we haven't provided the path
  logs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/log/'



