scrape_configs:
  - job_name: 'BUYER-SERVICE-INPUT'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['localhost:8085']
        labels:
          application: 'Buyer-Service-Metrics'

  - job_name: 'SELLER-SERVICE-INPUT'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'localhost:8086' ]
        labels:
          application: 'Seller-Service-Metrics'